### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by EqlipseD** [Nubebuster/Mining-Turtles#3]
If you command it to go up with any script it will break itself over and over collecting tons of sponge. I have not tested any other direction however.

**Comment by NubeBuster** [comment]
I can't reproduce the bug. Could you show me your scripts and check for stacktraces. Maybe even make a video :dancers: ?

**Comment by NubeBuster** [comment]
Previously:

> Sure, I am running the original scripts that comes default. I will make a video and upload it when I can. 
> Just a heads up, it happens when I do /t <turtlename> up excavate 3, and any other script as long as the direction is up and there is nothing above it but air. >- you

The command "/t <turtlename> up excavate 3" is not in the correct syntax.
I didnt realise I made the direction "up" possible. I'll investagate now.

**Comment by NubeBuster** [comment]
Haha, I've found the bug. I didn't intend to make the directions "up" and "down". I'm removing them in update 1.2.
You should instead write your own script for excavating up.
I'll send you 1.2 for 1.8.3 in a moment.

**Comment by NubeBuster** [comment]
Here it is: http://www.mediafire.com/download/d01pk09f2e1luyh/Mining_Turtles_1.2_for_1.8.3.jar

**Comment by EqlipseD** [comment]
Awesome, thank you very much sir.
